apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "task-manager.backend.fullname" . }}
  namespace: {{ include "task-manager.namespace" . }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.backend.containerPort | quote }}
  NODE_ENV: {{ .Values.backend.env.nodeEnv | quote }}
  APP_VERSION: {{ .Values.backend.env.appVersion | quote }}
  APP_IMAGE_TAG: {{ .Values.backend.image.tag | quote }}
  APP_STORAGE_MODE: {{ ternary "persistent-volume" "ephemeral-emptydir" .Values.backend.persistence.enabled | quote }}
  CORS_ORIGIN: {{ .Values.backend.env.corsOrigin | quote }}
  DB_HOST: {{ printf "%s-rw" (include "task-manager.db.clusterName" .) | quote }}
  DB_PORT: "5432"
  DB_POOL_MAX: {{ .Values.backend.env.dbPoolMax | quote }}
  DB_IDLE_TIMEOUT_MS: {{ .Values.backend.env.dbIdleTimeoutMs | quote }}
  DB_CONNECTION_TIMEOUT_MS: {{ .Values.backend.env.dbConnectionTimeoutMs | quote }}
  DB_INIT_RETRY_DELAY_MS: {{ .Values.backend.env.dbInitRetryDelayMs | quote }}
  MAX_UPLOAD_SIZE_BYTES: {{ .Values.backend.env.maxUploadSizeBytes | quote }}
  UPLOAD_DIR: {{ .Values.backend.persistence.mountPath | quote }}
