apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager.secretName" . }}
  namespace: {{ include "task-manager.namespace" . }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.bootstrap.username | quote }}
  password: {{ .Values.database.bootstrap.password | quote }}
  database: {{ .Values.database.bootstrap.database | quote }}
