{{- if and .Values.backend.persistence.enabled (not .Values.backend.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "task-manager.uploadsPvcName" . }}
  namespace: {{ include "task-manager.namespace" . }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.backend.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  {{- end }}
{{- end }}
